platform :ios, '8.0'
use_frameworks!

target 'QSWB' do
#Networking
pod 'Alamofire'
pod 'RealmSwift'
pod 'ObjectMapper'
pod 'SwiftyJSON'

#AutoLayout
pod 'SnapKit'

#Image
pod 'Kingfisher'

#UI
pod 'SVProgressHUD'
end